language: c
arch:
  - ppc64le

os: linux

sudo: required

services:
  - docker

script:
#   - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - make build -e DEVFLAG=false
  - docker images|grep harbor